language: android
cache: false
sudo: false
env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
    - ANDROID_TARGET=android-22

jdk:
  - oraclejdk7

android:
  components:
     - tools
     - platform-tools
     - android-22
     - build-tools-22.0.1
     - extra

  licenses:
     - 'android-sdk-license-.+'

script:
  - travis/build_app.sh
after_script:
  - travis/test_results.sh
